version: '2.1'

services:
  nginx:
    build: ./nginx
    restart: always
    container_name: ${NGINX_CONTAINER}
    ports:
      - ${NGINX_PROT}:80
      - ${NGINX_SSL_PROT}:443
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/
      - ${NGINX_SSL}:/etc/nginx/ssl/
      - ${APP_CODE_PATH}:/usr/share/nginx/html
      - ${NGINX_LOG}:/var/log/nginx
    logging:
      driver: ${LOG_DRIVER}
      options:
          max-file: ${MAX_FILE}
          max-size: ${MAX_SIZE}
    networks:
      - frontend

networks:
  frontend:
    name: ${FRONTEND_NETWORK_NAME}
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GETWAY}